version: '2'

services:

  mumble_server:
    image: ernestgwilsonii/docker-raspberry-pi-mumble-server:1.3.4
    hostname: mumble-server
    ports:
      - "64738:64738/udp"
      - "64738:64738/tcp"
    networks:
      - mumble-net1
    volumes:
      - "/opt/mumble-server/mumble-server.ini:/etc/mumble-server.ini"
      - "/opt/mumble-server:/var/lib/mumble-server"             
      - "/opt/mumble-server/logs:/var/log/mumble-server"
    privileged: true
    restart: always
    network_mode: "host"
    labels:
            io.balena.features.kernel-modules: '1'

networks:
  mumble-net1:
