version: '2'

volumes:
  volume_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/mumble-server/mumble-server.ini
  volume_2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/mumble-server
  volume_3:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/mumble-server/logs

services:

  mumble_server:
    image: ernestgwilsonii/docker-raspberry-pi-mumble-server:1.3.4
    hostname: mumble-server
    ports:
      - "64738:64738/udp"
      - "64738:64738/tcp"
    networks:
      - mumble-net1
    volumes:
      - "volume_1:/etc/mumble-server.ini"
      - "volume_2:/var/lib/mumble-server"             
      - "volume_3:/var/log/mumble-server"
    privileged: true
    restart: always
    network_mode: "host"
    labels:
            io.balena.features.kernel-modules: '1'

networks:
  mumble-net1:
