version: '2'

services:

  mumble_server:
#     image: ernestgwilsonii/docker-raspberry-pi-mumble-server:1.3.4
    hostname: mumble-server
    ports:
      # Mumble Control TCP 64738
      - mode: host
        target: 64738
        published: 64738
        protocol: tcp
      # Mumble Audio UDP 64738
      - mode: host
        target: 64738
        published: 64738
        protocol: udp
    networks:
      - mumble-net1
    volumes:
      - type: bind
        source: /opt/mumble-server/mumble-server.ini
        target: /etc/mumble-server.ini
      - type: bind
        source: /opt/mumble-server
        target: /var/lib/mumble-server              
      - type: bind
        source: /opt/mumble-server/logs
        target: /var/log/mumble-server
    privileged: true
    restart: always
    network_mode: "host"
    labels:
            io.balena.features.kernel-modules: '1'

networks:
  mumble-net1:
